### ISSUE TITLE
Check if the user already granted permissions

### ISSUE THREAD

**Issue by binho** [rbaumbach/InstagramSimpleOAuth#4]
How can I check if the user already granted Instagram permission?
Thanks!

**Comment by rbaumbach** [comment]
What do you mean by permission?

**Comment by binho** [comment]
The user already authenticated to Instagram (I have a valid token).

**Comment by rbaumbach** [comment]
If you know you have a valid token, I'm assuming it's persisted on the device somewhere?  Once you make the call to get the token and get a successful response from Instagram, you can use the Keychain to store it on the device for future usage.

If this isn't what you are looking for, I'm a little confused as this framework provides a means to login to Instagram to get a Token to be persisted (or not and you can make a call to get the token each time with this view controller).  The handling of the token itself to provide the app to make further API calls will have to be done on your end.
